/**
 * Writes docs/_generated/directory-map.md: every file under docs/, one line
 * each, grouped by folder. A listing, not a map (CF-05): docs/index.md says how
 * the layers relate; this says what each file is for.
 *
 * Nothing here is written by hand. A file's line is its frontmatter
 * `description`; a folder's line is its `index.md` description, or, for a
 * layer folder without one, the "Holds" cell of the Layers table in
 * docs/index.md. Never loaded by agents (docs/index.md, "Never").
 *
 *   yarn directory-map           write it
 *   yarn directory-map --check   exit 1 if it is out of date
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { listMarkdown, readMarkdown, readText, REPO_ROOT } from "./lib/docs.ts";
import { loadToolkit } from "./lib/toolkit.ts";

// An overlay leaves the host repo's docs alone (report §1, adoption tiers).
if (loadToolkit().tier !== "starter") {
  console.log(
    "directory-map — skipped: the overlay tiers do not map host docs.",
  );
  process.exit(0);
}

const OUT = "docs/_generated/directory-map.md";
const check = process.argv.includes("--check");

const files = listMarkdown("docs").filter(
  (f) => !f.startsWith("docs/_generated/"),
);

/** `docs/design/` → "Loops and Recipe A (…), …" from the index's Layers table. */
function layerPurposes(): Map<string, string> {
  const purposes = new Map<string, string>();
  for (const line of readText("docs/index.md").split("\n")) {
    const cells = line.split("|").map((c) => c.trim());
    const where = cells[2]?.match(/^`(docs\/[a-z-]+)\/(?:<[a-z]+>\/)?`$/);
    if (where && cells[3]) purposes.set(where[1]!, cells[3]);
  }
  return purposes;
}

const cell = (value: unknown) =>
  String(value ?? "")
    .replace(/\|/g, "\\|")
    .replace(/\s+/g, " ")
    .trim();

const fromHere = (target: string) =>
  path.posix.relative("docs/_generated", target);

const purposes = layerPurposes();

/** Directory → its files, the docs/ root first, each folder's index.md first. */
const byFolder = new Map<string, string[]>();
for (const file of files) {
  const dir = path.posix.dirname(file);
  byFolder.set(dir, [...(byFolder.get(dir) ?? []), file]);
}
const folders = [...byFolder.keys()].sort((a, b) =>
  a === "docs" ? -1 : b === "docs" ? 1 : a.localeCompare(b),
);
const isIndex = (file: string) => path.posix.basename(file) === "index.md";

const sections: string[] = [];
for (const dir of folders) {
  const folderFiles = byFolder
    .get(dir)!
    .sort((a, b) =>
      isIndex(a) === isIndex(b) ? a.localeCompare(b) : isIndex(a) ? -1 : 1,
    );
  const folderIndex = `${dir}/index.md`;
  const purpose =
    dir === "docs"
      ? "The map of the practice."
      : (purposes.get(dir) ??
        (existsSync(path.join(REPO_ROOT, folderIndex))
          ? readMarkdown(folderIndex).frontmatter?.description
          : undefined));
  sections.push("", `## \`${dir}/\``, "");
  if (purpose) sections.push(cell(purpose), "");
  sections.push("| File | What it is for | Status |", "| --- | --- | --- |");
  for (const file of folderFiles) {
    const fm = readMarkdown(file).frontmatter ?? {};
    sections.push(
      `| [\`${path.posix.basename(file)}\`](${fromHere(file)}) | ${cell(fm.description)} | ${cell(fm.status)} |`,
    );
  }
}

const out = [
  "---",
  "title: Directory map — every file, one line each",
  "description: Read when you want to know what a file under docs/ is for without opening it; generated from each file's frontmatter.",
  "layer: decisions",
  "status: adopted",
  "---",
  "",
  "# Directory map",
  "",
  `Every markdown file under \`docs/\` (${files.length}), grouped by folder. Generated by \`yarn directory-map\` from each file's \`description\`, which is written as a trigger: it says when to read the file. Do not edit by hand; CI fails when this is out of date. How the layers relate, and what loads when, is in [\`docs/index.md\`](../index.md).`,
  ...sections,
  "",
].join("\n");

const target = path.join(REPO_ROOT, OUT);
const current = existsSync(target) ? readFileSync(target, "utf8") : null;
if (check) {
  if (current !== out) {
    console.error(
      `directory-map — ${OUT} is out of date; run \`yarn directory-map\` and commit it.`,
    );
    process.exit(1);
  }
  console.log(`directory-map — up to date (${files.length} files).`);
} else {
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, out);
  console.log(`directory-map — ${files.length} files → ${OUT}`);
}
